fix(ci): pin sentence transformers to avoid dependency on ffmpeg (#1106)
With sentence-transformers v5.4.0, an import of torch-vision is done,
that requires ffmpeg to be installed in the system. This is making our
sanity checks fail on this project. The proposed solution is to pin the
sentence transformers version to the latest one that did not do the
import, i.e. 5.3.0.

Example of sanity check that was failing:
https://github.com/huggingface/optimum-neuron/actions/runs/24494266166/job/71585594578#step:3:488

Excerpt:
<details>

```
  File "/home/runner/work/optimum-neuron/optimum-neuron/optimum/exporters/neuron/convert.py", line 64, in <module>
    from sentence_transformers import SentenceTransformer
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 15, in <module>
    from sentence_transformers.base.sampler import DefaultBatchSampler, MultiDatasetDefaultBatchSampler
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/sentence_transformers/base/__init__.py", line 4, in <module>
    from .model import BaseModel
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/sentence_transformers/base/model.py", line 30, in <module>
    from sentence_transformers.base.modality import format_modality, infer_batch_modality
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/sentence_transformers/base/modality.py", line 14, in <module>
    from sentence_transformers.base.modality_types import (
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/sentence_transformers/base/modality_types.py", line 16, in <module>
    from torchcodec.decoders import AudioDecoder, VideoDecoder
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/__init__.py", line 10, in <module>
    from . import decoders, samplers  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/decoders/__init__.py", line 7, in <module>
    from .._core import AudioStreamMetadata, VideoStreamMetadata
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/_core/__init__.py", line 8, in <module>
    from ._metadata import (
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/_core/_metadata.py", line 16, in <module>
    from torchcodec._core.ops import (
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/_core/ops.py", line 84, in <module>
    load_torchcodec_shared_libraries()
  File "/home/runner/work/optimum-neuron/optimum-neuron/aws_neuron_venv_pytorch/lib/python3.11/site-packages/torchcodec/_core/ops.py", line 69, in load_torchcodec_shared_libraries
    raise RuntimeError(
RuntimeError: Could not load libtorchcodec. Likely causes:
          1. FFmpeg is not properly installed in your environment. We support
             versions 4, 5, 6 and 7.
          2. The PyTorch version (2.8.0+cpu) is not compatible with
             this version of TorchCodec. Refer to the version compatibility
             table:
             https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-torchcodec.
          3. Another runtime dependency; see exceptions below.
        The following exceptions were raised as we tried to load libtorchcodec:
        
[start of libtorchcodec loading traceback]
FFmpeg version 7: libavutil.so.59: cannot open shared object file: No such file or directory
FFmpeg version 6: libavutil.so.58: cannot open shared object file: No such file or directory
FFmpeg version 5: libavutil.so.57: cannot open shared object file: No such file or directory
FFmpeg version 4: libavutil.so.56: cannot open shared object file: No such file or directory
[end of libtorchcodec loading traceback].
```
</details>